[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ti-84-python"
version = "1.62.0"
description = "TI-84 Plus CE-T Python Edition Applications"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coverage==7.14.0"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
