[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ti-84-python"
version = "1.70.0"
description = "TI-84 Plus CE-T Python Edition Applications"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coverage==7.14.0",
    "flake8==7.3.0",
    "python_minifier==3.2.0",
    "sphinx",
    "sphinx_rtd_theme==3.1.0",
    "vulture==2.16"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
