r"""
Utility script to build a launcher script for the bat call phase analyser.

The input is a JSON format analysis file generated by the Spectrogram Viewer bat call
recording analyser. A cut-down version of a file, illustrating only the fields
required by this utility, is shown below:

.. code-block:: json

    {
        "input": "BD-A-99-001.wav",
        "analysis_mode": "time-expansion",
        "pulses": [
            {
                "real_start_time_s": 0.007501133786848073,
                "real_end_time_s": 0.00943310657596372,
                "real_peak_time_s": 0.008090702947845805,
            }
        ]
    }

The "input" (or "input_file") field specifies the filename for the original recording. The
"analysis_mode" may be "heterodyne" or "time-expansion" and the "pulses" field specifies
a list of pulse objects. Only the fields shown, above, are used by this tool

This script reads the JSON file and cconverts the list of pulses into a to a Tuple of values::

    (start, end, peak, start, end, peak, ...)

This information is then passed to the pulse timing analyser that generates the following
information for each pulse:

- List of pulse widths
- List of pulse repetition interval (PRI) values
- List of delta-PRI (DPRI) values

The timing information is then written to the launcher script necessary to run the bat call
phase analyser.

Example usage from the root folder of the project::

    python src/support/extract_timings.py -i data/spectrogram/BD-A-99-001-analysis.json -o src/examples/batbuzz.py

A utility script is provided in the "scripts" folder to run the minimiser::

    scripts/extract-timings.sh -i data/spectrogram/BD-A-99-001-analysis.json -o src/examples/batbuzz.py

The resulting script can then be minified and transferred to the calculator along with
the bat phase analysis library module and then run to generate the pulse characteristics.

For more information on the Bat Call Analyser, Phase Analyser and Spectrogram Viewer see:

- The Spectrogram Viewer repository - https://github.com/davewalker5/SpectrogramViewer
- The Field Notes Journal web site - https://fieldnotesjournal.uk
"""


import argparse
import os
from pathlib import Path
from extract_pulses import load_pulse_json
from batpulse import analyse_pulse_timings

DEFAULT_TEMPLATE = Path(__file__).parent.parent.parent / "data" / "templates" / "bat_phase_analysis.py"


def read_template(template_file_path: str | Path) -> str:
    """
    Read the contents of the template script

    :param template_file_path: Path to the template
    :return: Contents of the template
    """
    with open(template_file_path, "r", encoding="utf-8") as f:
        return f.read()


def build_analysis_script(
        template: str,
        widths: tuple | list,
        pri: tuple | list,
        dpri:  tuple | list
) -> str:
    """
    Replace placeholders in the template script content with the values for
    the call pulses

    :param template: Template script contents
    :param parameters: Tuple of pulse properties
    :return: Updated script content
    """
    return template \
        .replace("$WIDTHS", str(tuple(widths))) \
        .replace("$PRI", str(tuple(pri))) \
        .replace("$DPRI", str(tuple(dpri)))


def write_analysis_script(output_path: str | Path, script: str):
    """
    Write the modelling script for a species

    :param output_path: Path to the folder where the script is to be written
    :param script: File contents
    """
    with open(output_path, "w", encoding="utf-8") as f:
        return f.write(script)


def main():
    """
    Main entry point for the seasonal modelling per-species wrapper script builder
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("-i", "--input", required=True, help="Path to the input JSON file")
    parser.add_argument("-t", "--template", default=DEFAULT_TEMPLATE,
                        help="Template used to build the bat phase analysis script")
    parser.add_argument("-o", "--output", required=True, help="Path to the output script")
    args = parser.parse_args()

    # Load the pulse data from the JSON file and generate the pulse timing information
    _, _, pulses = load_pulse_json(args.input)
    widths, pri, _, dpri = analyse_pulse_timings(pulses)

    # Load the template and generate the script content
    template = read_template(args.template)
    script = build_analysis_script(template, widths, pri, dpri)

    # Write the script
    write_analysis_script(args.output, script)


if __name__ == "__main__" and "DOCBUILD" not in os.environ:
    main()
