r"""
Utility script to build a launcher script for the bat call pulse analyser.

The input is a JSON format analysis file generated by the Spectrogram Viewer bat call
recording analyser. A cut-down version of a file, illustrating only the fields
required by this utility, is shown below:

.. code-block:: json

    {
        "input": "BD-A-99-001.wav",
        "analysis_mode": "time-expansion",
        "pulses": [
            {
                "real_start_time_s": 0.007501133786848073,
                "real_end_time_s": 0.00943310657596372,
                "real_peak_time_s": 0.008090702947845805,
            }
        ]
    }

The "input" (or "input_file") field specifies the filename for the original recording. The
"analysis_mode" may be "heterodyne" or "time-expansion" and the "pulses" field specifies
a list of pulse objects. Only the fields shown, above, are used by this tool

This script reads the JSON file and cconverts the list of pulses into a to a Tuple of values::

    (start, end, peak, start, end, peak, ...)

The pulse information is then written to the launcher script necessary to run the bat call
pulse timing analyser.

Example usage from the root folder of the project::

    python src/support/extract_pulses.py -i data/spectrogram/BD-A-99-001-analysis.json -o src/examples/batchart.py

A utility script is provided in the "scripts" folder to run the minimiser::

    scripts/extract-pulses.sh -i data/spectrogram/BD-A-99-001-analysis.json -o src/examples/batchart.py

The resulting script can then be minified and transferred to the calculator along with
the bat pulse analysis library module and then run to graph the pulse characteristics.

For more information on the Bat Call Analyser and Spectrogram Viewer see:

- The Spectrogram Viewer repository - https://github.com/davewalker5/SpectrogramViewer
- The Field Notes Journal web site - https://fieldnotesjournal.uk
"""


import json
import os
import argparse
from pathlib import Path
from datetime import datetime

DEFAULT_TEMPLATE = Path(__file__).parent.parent.parent / "data" / "templates" / "bat_pulse_chart.py"


def print_message(message: str) -> None:
    """
    Show a timestamped message

    :param message: Message text
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"{timestamp} : {message}")


def round_to_significant(value: float, places: int = 3) -> float:
    """
    Round a float to the specified number of significant figures

    :param float: Value to round
    :param places: Number of places
    :return: Rounded float
    """
    return None if value is None else float(f"{value:.{places}g}")


def load_pulse_json(
        input_file_path: str | Path,
        start_index: int = 1,
        end_index: int = None
) -> dict:
    """
    Load the consensus parameter set from the seasonal modelling consensus JSON
    file for the species

    :param input_file_path: JSON file path
    :return: Tuple of the species namd and the filtered list of parameters
    """
    print_message(f"Loading {input_file_path}")
    with open(input_file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Extract the original input file and extract it's name as the source
    source_file = data.get("input", data.get("input_file", None))
    source = Path(source_file).name
    print_message(f"Source file name {source}")

    # Extract the analysis mode
    mode = data["analysis_mode"]
    print_message(f"Detected mode {mode}")

    # Extract only the required range of pulses
    pulses = data["pulses"]
    max_pulse_index = len(pulses)
    print_message(f"Detected {max_pulse_index} pulses")

    if start_index is None or start_index <= 0:
        start_index = 1

    if end_index is None or end_index > max_pulse_index:
        end_index = max_pulse_index

    pulses = pulses[start_index - 1:end_index]
    print_message(f"{len(pulses)} pulses remain after extracting the slice from {start_index} to {end_index}")

    # Extract the pulses. Use the "real" start time, end time and peak timing fiels.
    # For heterodyne recordings, these will be the same as the "non-real" versions
    # but for time expansion the "non-real" versions reflect the expanded timings
    timings = []
    for pulse in pulses:
        timings.append(round_to_significant(pulse["real_start_time_s"], 3))
        timings.append(round_to_significant(pulse["real_end_time_s"], 3))
        timings.append(round_to_significant(pulse["real_peak_time_s"], 3))

    print_message(f"Extracted {len(timings) // 3} sets of timing values")
    return source, mode, tuple(timings)


def read_template(template_file_path: str | Path) -> str:
    """
    Read the contents of the template script

    :param template_file_path: Path to the template
    :return: Contents of the template
    """
    print_message(f"Loading template {template_file_path}")
    with open(template_file_path, "r", encoding="utf-8") as f:
        return f.read()


def build_analysis_script(template: str, pulses: tuple) -> str:
    """
    Replace placeholders in the template script content with the values for
    the call pulses

    :param template: Template script contents
    :param parameters: Tuple of pulse properties
    :return: Updated script content
    """
    return template.replace("$PULSES", str(pulses))


def write_analysis_script(output_path: str | Path, script: str):
    """
    Write the modelling script for a species

    :param output_path: Path to the folder where the script is to be written
    :param script: File contents
    """
    print_message(f"Writing launcher {output_path}")
    with open(output_path, "w", encoding="utf-8") as f:
        return f.write(script)


def main():
    """
    Main entry point for the seasonal modelling per-species wrapper script builder
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("-i", "--input", required=True, help="Path to the input JSON file")
    parser.add_argument("-t", "--template", default=DEFAULT_TEMPLATE,
                        help="Template used to build the bat call analysis script")
    parser.add_argument("-si", "--start-index", type=int, default=1, help="Index of first pulse to include")
    parser.add_argument("-ei", "--end-index", type=int, default=None, help="Index of last pulse to include")
    parser.add_argument("-o", "--output", required=True, help="Path to the output script")
    args = parser.parse_args()

    # Load the data and extract the pulse information into a tuple
    _, _, pulses = load_pulse_json(args.input, args.start_index, args.end_index)

    # Load the template and generate the script content
    template = read_template(args.template)
    script = build_analysis_script(template, pulses)

    # Write the script
    write_analysis_script(args.output, script)


if __name__ == "__main__" and "DOCBUILD" not in os.environ:
    main()
